#! /usr/bin/env node

const path = require('path')
const dotEnvPath = path.relative(__dirname, path.join(process.cwd(), './dotenv.js'))
require(dotEnvPath)()
require('../helpers/bootstrapDatabase')(null, function(){
  process.exit()
})
