#! /usr/bin/env node
var seeder = require('mongoose-seed')
const dotEnvPath = path.relative(__dirname, path.join(process.cwd(), './dotenv.js'))
require(dotEnvPath)()

var requireDir = require('require-dir')
var seeds = {
  Brigade: require('../seeds/Brigade'),
  Events: require('../seeds/Events'),
  Posts: require('../seeds/Posts'),
  Projects: require('../seeds/Projects'),
  Users: require('../seeds/Users')
}
for (seedName in seeds) {
  if (typeof seeds[seedName] === 'function') seeds[seedName] = seeds[seedName]()
  seeds[seedName] = {
    model: seedName,
    documents: seeds[seedName]
  }
}

seeder.connect(process.env.MONGODB_URI, function () {
  seeder.loadModels([
    'models/Users.js',
    'models/Posts.js',
    'models/Events.js',
    'models/Brigade.js',
    'models/Projects/index.js',
    'models/Checkins/index.js'
  ])
  seeder.clearModels([
    'Users',
    'Posts',
    'Events',
    'Brigade',
    'Projects',
    'Checkins'
  ], function () {
    seeder.populateModels(seeds,function(){
      console.log('Database seeding complete. Please restart your Brigadehub server.')
      process.exit()
    })
  })
})

// connect(function(err, disconnect){
//
//   seeder.seed(data, {dropCollections: true}).then(function(dbData) {
//
//   }).catch(function(err) {
//
//   })
// })
//
// var models = path.resolve("./models/*")
// console.log(models)
// var db = goosestrap(process.env.MONGODB ||  process.env.MONGOLAB_URI, models)
//
//
// console.log(seeds)
// var seeds = requireDir('../seeds/development')
// console.log(seeds)
// seeds.Brigade = seeds.Brigade()
// console.log(seeds)
//
// seed = new Seedling(db, seeds)
// seed.clear(function(){
//   seed.create(function(err){
//     if(err) throw err
//     console.log('Database seeding complete. Please restart your server.')
//     process.exit()
//   })
// })
